name: .NET Core Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master     

jobs:
  build:
    name: Build Package 
    runs-on: windows-latest # using windows agent for net462 build.

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: Restore
      run: dotnet restore

