name: "Build Test and Pub"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master     

env:
  NETCORE_VERSION: '3.1.402'  

jobs:
#================================================================================================
#=========================== Build, Unit Test, Gen and Publish Client ===========================
#================================================================================================
    build:
        name: Build, Unit Test and Publish Client
        runs-on: [self-hosted, linux, x64]
        steps:
        - uses: actions/checkout@v2
        - name: Setup .NET Core SDK ${{ env.NETCORE_VERSION }}
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.NETCORE_VERSION }}
        - name: Restore packages     
